# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "i18n_generator"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Young"]
  s.date = "2013-09-08"
  s.description = "Generates locale-specific resource bundles (.properties files) from translations held in an Excel spreadsheet"
  s.email = "robyoung26@gmail.com"
  s.executables = ["i18n_generate"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/i18n_generate",
    "examples/example_labels.xlsx",
    "i18n_generator.gemspec",
    "lib/i18n_generator.rb",
    "lib/i18n_generator/cli.rb",
    "lib/i18n_generator/excel_parser.rb",
    "lib/i18n_generator/label.rb",
    "lib/i18n_generator/label_writer.rb",
    "test/excel_parser_test.rb",
    "test/helper.rb",
    "test/label_test.rb",
    "test/label_writer_test.rb"
  ]
  s.homepage = "http://github.com/rulefinancial/i18n_generator"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Generates locale-specific resource bundles from Excel-based translations"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<roo>, ["~> 1.12.1"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.18.1"])
      s.add_runtime_dependency(%q<rubyzip>, ["< 1.0.0"])
      s.add_development_dependency(%q<minitest>, ["~> 5.0.6"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<roo>, ["~> 1.12.1"])
      s.add_dependency(%q<thor>, ["~> 0.18.1"])
      s.add_dependency(%q<rubyzip>, ["< 1.0.0"])
      s.add_dependency(%q<minitest>, ["~> 5.0.6"])
      s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<roo>, ["~> 1.12.1"])
    s.add_dependency(%q<thor>, ["~> 0.18.1"])
    s.add_dependency(%q<rubyzip>, ["< 1.0.0"])
    s.add_dependency(%q<minitest>, ["~> 5.0.6"])
    s.add_dependency(%q<rdoc>, ["~> 4.0.1"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

